export const PROJECTS_REQUEST = "PROJECTS_REQUEST";
export const PROJECTS_REQUEST_SUCCESS = "PROJECTS_REQUEST_SUCCESS";
export const PROJECTS_REQUEST_ERROR = "PROJECTS_REQUEST_ERROR";

export const SET_PROJECT_IMAGE = "SET_PROJECT_IMAGE";
